### ISSUE TITLE
GHC 9.0 Compatibility: TypeApplications and ticked promoted constructors

### ISSUE THREAD

**Issue by konn** [fourmolu/fourmolu#57]
Currently, fourmolu formats type application with ticked promoted constructor with space inserted in-between:

before:
```hs
foo @'True
```

after:

```hs
foo @ 'True
```

This works fine with GHC <= 8.10.

However, as GHC 9.0 introduces whitespace-sensitive parsing of operators ([1], [2]), the above result makes ghc complaining that "Variable not in scope: (@)".

Dependently-typed programs suffer much from this behaviour, and hence a whitespace MUST NOT be inserted.

[1]: https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0229-whitespace-bang-patterns.rst
[2]: https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#whitespace-sensitive-and-

**Comment by georgefst** [comment]
Oof, that's ugly even now. I didn't know that would actually parse.

Anyway, fortunately, as has been commented on the issue you opened for Ormolu (tweag/ormolu#680), this has already been fixed there. So it just remains for us to merge upstream improvements since the `1.3.0` release in September. Should be easy enough - there hasn't been too much [activity](https://github.com/tweag/ormolu/commits/master), and at a glance, I don't foresee any conflicts.
